=== Kamilly-cod/LenguajeDeMarcas/DTD_ejercicios/ejercicioDTD1/enunciado.dtd
<!ELEMENT curriculum (datosPersonales,detalles,descripcion,formacionAcademica,formacionProfesional,competencia)>
    <!ELEMENT datosPersonales EMPTY>
    <!ATTLIST datosPersonales nombre CDATA #REQUIRED>
    <!ATTLIST datosPersonales apellidos CDATA #REQUIRED>
    <!ATTLIST datosPersonales nacimiento CDATA #REQUIRED>

    <!ELEMENT detalles (localizacion,datosContacto)>
    <!ELEMENT localizacion EMPTY>
    <!ATTLIST localizacion residencia CDATA #REQUIRED>
    <!ATTLIST localizacion ciudad CDATA #REQUIRED>
    <!ATTLIST localizacion país CDATA #REQUIRED>

    <!ELEMENT datosContacto EMPTY>
    <!ATTLIST datosContacto teléfono CDATA #REQUIRED>
    <!ATTLIST datosContacto correo CDATA #REQUIRED>
    <!ATTLIST datosContacto linkedIn CDATA #REQUIRED>

    <!ELEMENT descripcion (#PCDATA)>

    <!ELEMENT formacionAcademica (areaEstudio,aptitudes)>
    <!ELEMENT areaEstudio EMPTY >
    <!ATTLIST areaEstudio fechaLocal CDATA  #REQUIRED>
    <!ATTLIST areaEstudio areaEstudio CDATA #REQUIRED>

    <!ELEMENT aptitudes EMPTY >
    <!ATTLIST aptitudes apt1 CDATA #REQUIRED>
    <!ATTLIST aptitudes apt2 CDATA #REQUIRED>
    <!ATTLIST aptitudes apt3 CDATA #REQUIRED>
    <!ATTLIST aptitudes apt4 CDATA #REQUIRED>
    <!ATTLIST aptitudes apt5 CDATA #REQUIRED>
    <!ATTLIST aptitudes apt6 CDATA #REQUIRED>
    <!ATTLIST aptitudes apt7 CDATA #REQUIRED>

    <!ELEMENT formacionProfesional (areaProfesional,aptitudesP)>
    <!ELEMENT areaProfesional EMPTY>
    <!ATTLIST areaProfesional fecha CDATA #REQUIRED>
    <!ATTLIST areaProfesional local CDATA #REQUIRED>
    <!ATTLIST areaProfesional encargo CDATA #REQUIRED>
    <!ELEMENT aptitudesP EMPTY>
    <!ATTLIST aptitudesP apt1 CDATA #REQUIRED>
    <!ATTLIST aptitudesP apt2 CDATA #REQUIRED>
    <!ATTLIST aptitudesP apt3 CDATA #REQUIRED>
    
    <!ELEMENT competencia EMPTY>
    <!ATTLIST competencia idioma1 NMTOKEN #REQUIRED>
    <!ATTLIST competencia idioma2 NMTOKEN #REQUIRED>
    <!ATTLIST competencia idioma3 NMTOKEN #REQUIRED>

=== Kamilly-cod/LenguajeDeMarcas/almacenamiento2/DTD_ejercicios/ejercicioDTD1/ejercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "enunciado.dtd" >

<curriculum>
    <datosPersonales nombre="Kamilly" apellidos="Brito da Mata" nacimiento="20/02/2004"/>
    <detalles> 
        <localizacion residencia="Calle Roma, 13,"
            ciudad="Madrid," país="España"/>
        <datosContacto teléfono="(613)65-41-65" correo="kamillybrittodm@gmail.com" linkedIn="KamillyBM" />
    </detalles>
        <descripcion>
            Mensajero con 13 años de experiencia en transporte de documentos y paquetes urgentes a proveedores y clientes, utilizando los medios disponibles y siempre en los plazos acordados.
        </descripcion>
        <formacionAcademica>
            <areaEstudio fechaLocal="Junio 2005 - IES Padre Luis Coloma Jerez de la Frontera" areaEstudio="FP de Grado Medio en Gestión Administrativa"
            />
            <aptitudes apt1="Separación de la carga" apt2="Cumplimentación de documentos" apt3="Reparto de cartas y paquetería" apt4="Reparto de cartas y paquetería" apt5=" Clasificación postal" apt6="Compromiso y profesionalidad" apt7="Familiaridad con distintos GPS"/>
        </formacionAcademica>

        <formacionProfesional>
            <areaProfesional fecha="Febrero 2016 – Actual" local="Local: Correos Express – Jerez de la Frontera" encargo="Mensajero" />
            <aptitudesP apt1= "Recogida a domicilio de sobres de documentos para su posterior envío mediante mensajería urgente." apt2="Presentación de documentos y notificaciones a diferentes entidades gubernamentales." apt3="Reparto de correspondencia y paquetes en coche y moto." />
        </formacionProfesional>
        <competencia idioma1= "inglês" idioma2="Português" idioma3="Español"/>
</curriculum>
